-- CreateTable
CREATE TABLE `purchase_requests` (
    `id` VARCHAR(191) NOT NULL,
    `date` DATETIME(3) NOT NULL,
    `pr_number` VARCHAR(191) NULL,
    `department` VARCHAR(191) NULL,
    `budget_number` VARCHAR(191) NULL,
    `fixed_asset_number` VARCHAR(191) NULL,
    `type` VARCHAR(191) NULL,
    `transportation` VARCHAR(191) NULL,
    `kind_of_request` VARCHAR(191) NULL,
    `acc` VARCHAR(191) NULL,
    `item_code` VARCHAR(191) NULL,
    `item_name` VARCHAR(191) NULL,
    `description_of_goods` VARCHAR(191) NULL,
    `specification` VARCHAR(191) NULL,
    `part` VARCHAR(191) NULL,
    `quantity` INTEGER NOT NULL,
    `unit` VARCHAR(191) NULL,
    `est_unit_price` DOUBLE NOT NULL,
    `est_amount` DOUBLE NOT NULL,
    `currency` VARCHAR(191) NULL,
    `req_delivery` DATETIME(3) NULL,
    `supplier` VARCHAR(191) NULL,
    `remark` VARCHAR(191) NULL,
    `purpose` VARCHAR(191) NULL,
    `requested` VARCHAR(191) NULL,
    `gen_manager` VARCHAR(191) NULL,
    `supervisor` VARCHAR(191) NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
