version: "3.9"

services:
  backend:
    build: .
    container_name: app-backend
    ports:
      - "0.0.0.0:${APP_PORT:-3210}:3000"
    env_file:
      - .env
    environment:
      - APP_PORT=3000
      - DATABASE_URL=mysql://${DB_USER:-root}:${DB_PASSWORD:-password}@${DB_HOST:-mysql-server}:${DB_PORT:-3306}/${DB_NAME:-database_name}
    volumes:
      - ./watched-folder:/app/watched-folder
      - ./logging:/app/logging
    networks:
      - cmwi-network
    restart: unless-stopped

networks:
  cmwi-network:
    name: cmwi-network
    external: true
