import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();
import bcrypt from 'bcrypt';

async function main() {
    await prisma.user.createMany({
        data: [
            {
                username: 'admin',
                name: 'Admin',
                password: await bcrypt.hash('admin', 10),
            }
        ],
    });


    await prisma.maker.createMany({
        data: [
            { name: 'NIPPON STEEL & SUMIKIN BUSAN MATEX CO,LTD' },
            { name: 'NIPPON STEEL & SUMIKIN BUSAN MATEX CO.LTD' },
            { name: 'TOUNETSU' },
            { name: 'ARO' },
            { name: 'CV Wahyu Arta Technic' },
            { name: 'TOYOKI' },
            { name: 'CV. WAHYU ARTHA' },
            { name: 'SMC' },
            { name: 'NICHEI' },
            { name: 'PT Tempsens Asia Jaya' },
            { name: 'PT TEMPSENS ASIA JAYA' },
            { name: 'TOYOTSU MACHINERY' },
            { name: 'JAPAN VALVE' },
            { name: 'KROM SCHRODER' },
            { name: 'TSUBAKI' },
            { name: 'CKD' },
            { name: 'AZBIL' },
            { name: 'SANKEN' },
            { name: 'NISSIN RIKEN' },
            { name: 'HOPE' },
            { name: 'SANKEN SANGYO KABUSHI KAISHI' },
            { name: 'PT KINARYA NUSANTARA SUKSESTY' },
            { name: 'THERMAL INSULATION TECH' },
            { name: 'Nippon Steel Trading Matex Co.,LTD' },
            { name: 'Toyotsu Machinery Corporation' },
            { name: 'NTN' },
            { name: 'TAIYO' },
            { name: 'NACHI' },
            { name: 'HANYOUNG' },
            { name: 'TAIWAN' },
            { name: 'SANLI/ TAIWAN' },
            { name: 'YUKEN' },
            { name: 'KCL' },
            { name: 'LUCKY DRAGON INTERNATIONAL CO., LTD.' },
            { name: 'PM ELECTRIC' },
            { name: 'SUMITOMO' },
            { name: 'DID' },
            { name: 'HORIUCHI MACHINERY' },
            { name: 'THK' },
            { name: 'NBK' },
            { name: 'MARTIN' },
            { name: 'LUCKY DRAGON INTERNATIONAL' },
            { name: 'SHINPO' },
            { name: 'KHK' },
            { name: 'CHANTO TAIWAN' },
            { name: 'HIROSE VALVES' },
            { name: 'CML' },
            { name: 'PT. INOX PRIMA' },
            { name: 'PT ARPHUS REKA MANDIRI' },
            { name: 'FYH' },
            { name: 'PT MISUMI INDONESIA' },
            { name: 'PT Zenbi Machinery And Electronics Indonesia' },
            { name: 'CLC' },
            { name: 'HER YIH HYDRAULIC' },
            { name: 'COOLBIT' },
            { name: 'MODENA' },
            { name: 'PT. SINAR MUTIARA CAKRABUANA' },
            { name: 'PT STAHLINDO SURFACING INDONESIA' },
            { name: 'LOKAL' },
            { name: 'MADE IN ITALY' },
            { name: 'NIPPON FOW CELL' },
            { name: 'FAWAZ' },
            { name: 'YKT GEAR' },
            { name: 'TOYOTSU MACHINERY Corp.' },
            { name: 'KITZ' },
            { name: 'SINTO' },
            { name: 'NOHKEN' },
            { name: 'MIKI PULLY' },
            { name: 'FBN' },
            { name: 'MISUMI' },
            { name: 'KIWA MACHINERY CO., LTD' },
            { name: 'ABBA LINEAR TECH CO.LTD' },
            { name: 'KASUGA' },
            { name: 'OILES' },
            { name: 'TOYOOKI' },
            { name: 'TUFFIADI' },
            { name: 'TAIHEI BOEKI' },
            { name: 'TOYOTSU' },
            { name: 'OSAKA NISSYO INSTRUMENT CO. LTD' },
            { name: 'NABEYA' },
            { name: 'TAKIGEN' },
            { name: 'PT. TUFFIADI' },
            { name: 'NAGANO KEIKI' },
            { name: 'NOK' },
            { name: 'PT. GERONIMO' },
            { name: 'NIKKI' },
            { name: 'TOYOTSU MACHINERY CORPORATION' },
            { name: 'FUJI SEIMITSU' },
            { name: 'FAG' },
            { name: 'MITSUBOSHI' },
            { name: 'KANZAKI' },
            { name: 'KANZAKI KOKYUKOKI MFG CO LTD' },
            { name: 'KOSMEK' },
            { name: 'PT. PUSACO INTERNATIONAL' },
            { name: 'BANDO' },
            { name: 'KANZAKI / KITAGAWA' },
            { name: 'KITAGAWA' },
            { name: 'TOWA SEIDEN' },
            { name: 'MIHATA SEIKO' },
            { name: 'KIWA' },
            { name: 'CV Sinar Artha Technic' },
            { name: 'KIWA MACHINERY' },
            { name: 'KANZAKI/ KITAGAWA' },
            { name: 'OKUMA' },
            { name: 'RIX CO,.LTD.' },
            { name: 'FANUC' },
            { name: 'KANZAKI/ MIHARA' },
            { name: 'IKO' },
            { name: 'TSUBAKIMOTO CHAIN CORPORATION' },
            { name: 'FUJI ELECTRIC KOATSU FLEXIBLE HOSE CO.,LTD.' },
            { name: 'PT. NIKKO TEKNIK INDONESIA' },
            { name: 'PANASONIC' },
            { name: 'TEMPSENS' },
            { name: 'PRONA' },
            { name: 'PT Sinar Mutiara Cakrabuana' },
            { name: 'DAIMA II' },
            { name: 'WIKA' },
            { name: 'TSUBAKI / HITACHI' },
            { name: 'KOU CHUAN' },
            { name: 'VENN' },
            { name: 'SMC PNEUMATIC' },
            { name: 'ASAHI SUNAC' },
            { name: 'KANZAKI KOKYUKOKI Mfg Co Ltd' },
            { name: 'KUO CHUAN MACHINERY INDUSTRIAL CO.,LTD.' },
            { name: 'NACI' },
            { name: 'TACMINA' },
            { name: 'LAFERT' },
            { name: 'SHOWA' },
            { name: 'MITSUBISHI' },
            { name: 'UNID' },
            { name: 'C-KING' },
            { name: 'MIGISHITA' },
            { name: 'ORION' },
            { name: 'YAMAMOTO KEIKI INSTRUMENT' },
            { name: 'NKS' },
            { name: 'HORIBA' },
            { name: 'PARKINS' },
            { name: 'DUNGS' },
            { name: 'RIELLO' },
            { name: 'SIEMENS' },
            { name: 'BRAHMA' },
            { name: 'KAEL' },
            { name: 'PT LEITER INDONESIA / PT. STARK ASIA' },
            { name: 'CV. BETA GABERTA' },
            { name: 'GIULIANI ANELLO' },
            { name: 'TLV' },
            { name: 'PT. GANDOX CHEMICAL' },
            { name: 'KOBELCO' },
            { name: 'CV Beta Gaberta Mekanindo' },
            { name: 'KEYENCE' },
            { name: 'OMRON' },
            { name: 'TAKENAKA JAPAN' },
            { name: 'PT. GADING NUSA PERSADA' },
            { name: 'PATLITE' },
            { name: 'PHILIPS' },
            { name: 'MITSUBISHI ELECTRIC' },
            { name: 'KAWASAKI' },
            { name: 'PANASOINIC' },
            { name: 'ORIENTAL MOTOR' },
            { name: 'LUCKY DRAGON' },
            { name: 'FUJI ELECTRIC' },
            { name: 'FUJI ELECRIC' },
            { name: 'Nord-Lock' },
            { name: 'Omron' },
            { name: 'TDK -LAMBADA' },
            { name: 'Puji Electric' },
            { name: 'ZAHWAN' },
            { name: 'TOKYO RIKOSHO' },
            { name: 'NIPRON' },
            { name: 'SANYO DENKI' },
            { name: 'CHUBU MEIKIKO' },
            { name: 'LS' },
            { name: 'Legran' },
            { name: 'CUSTOM' },
            { name: 'COSMOS' },
            { name: 'MATSUYOSHI' },
            { name: 'DAIWA DENGYO' },
            { name: 'SAGINOMIYA' },
            { name: 'PLUS ELECTCRIC' },
            { name: 'MARPOSS' },
            { name: 'COSEL' },
            { name: 'YUTAKA' },
            { name: 'JSK' },
            { name: 'MIRO' },
            { name: 'IDEC' },
            { name: 'LECIP' },
            { name: 'IAI CORPORATION' },
            { name: 'SKYKIN' },
            { name: 'BUSMAN' },
            { name: 'Fuji Electric' },
            { name: 'PT. NIPPON STELL SUMIKIN BUSAN' },
            { name: 'PT. INDOMAKMUR MANDIRI' },
            { name: '0' },
            { name: 'NORD LOCK' },
            { name: 'ONO SOKI' },
            { name: 'IMF' },
            { name: 'HONEYWELL' },
            { name: 'ORIENTAL' },
            { name: 'MEIJI DENKI' },
            { name: 'PEPPERL FUCHS' },
            { name: 'ABC ALKALINE' },
            { name: 'FORT' },
            { name: 'PT FANUC INDONESIA' },
            { name: 'NSK' },
            { name: 'UNI-D' },
            { name: 'JAYA INDUKSI' },
            { name: 'NIHANA SEISAKUSHO' },
            { name: 'ASCO' },
            { name: 'SENTA ANDALAN KIMIA' },
            { name: 'ROTAMETER' },
            { name: 'SKF' },
            { name: 'YU-SHING' },
            { name: 'AICHI TOKEI' },
            { name: 'CV Sinar artha Technic' },
            { name: 'ELMECON' },
            { name: 'KUO CHUAN MACHINERY INDUSTRIAL CO.,LTD' },
            { name: 'PT Fanuc Indonesia' },
            { name: 'INOX' },
            { name: 'CV SENTA ANDALAN KIMIA' },
            { name: 'WAHYU ARTHA' },
            { name: 'ORIGINAL ORION' },
            { name: 'AFE' },
            { name: 'Kanzaki Kokyukoki Mfg Co Ltd' },
            { name: 'SINAR BUANA' },
            { name: 'HINODE' },
            { name: 'MINEZAWA' },
            { name: 'SCUH' },
            { name: 'SCUH + YAMATO' },
            { name: 'KOGANEI' },
            { name: 'MITSUBISHI MOTOR' },
            { name: 'DAIKIN' },
            { name: 'YOKOHAMA' },
            { name: 'JTEKT' },
            { name: 'NAGANO' },
            { name: 'PT Misumi Indonesia' },
            { name: 'Isuzu MFG Co Ltd' },
            { name: 'GTR' },
            { name: 'FUJI HENSOKUKI' },
            { name: 'ISUZU MFG. CO., LTD.' },
            { name: 'TAISEI KOGYO' },
            { name: 'IHI' },
            { name: 'FUJIKIN' },
            { name: 'Toyotsu Machinery Corp' },
            { name: 'DAIICHI KEIKI' },
            { name: 'PT Numacindo Karsakharisma' },
            { name: 'NISSEI' },
            { name: 'Toyotsu Machinery' },
            { name: 'PT PUTRA PARUNG JAYA' },
            { name: 'MITSHUBISHI ELEECTRIC' },
            { name: 'LINE SEIKI' },
            { name: 'SCHNEIDER' },
            { name: 'YASKAWA' },
            { name: 'TOSHIBA' },
            { name: 'SANYO' },
            { name: 'CIC' },
            { name: 'Autonics' },
            { name: 'FUJI ELECTIC' },
            { name: 'SIKA' },
            { name: 'MELCO TECHNOREX' },
            { name: 'ASAHI' },
            { name: 'PT SINTO INDONESIA' },
            { name: 'Tsubaki' },
            { name: 'PT.SINTO INDONESIA' },
            { name: 'ASB' },
            { name: 'UNITTA' },
            { name: 'PT Traktor Nusantara' },
            { name: 'CV.SINAR ARTHA' },
            { name: 'SINFONIA' },
            { name: 'MEIKIKOU' },
            { name: 'BUSCH' },
            { name: 'Oriental' },
            { name: 'YUEMA' },
            { name: 'EVACH' },
            { name: 'CV Wira Griya Mustika' },
            { name: 'YAMAMOTO KEIKI' },
            { name: 'TOYOTSU MACHINERY (PO : 296 01 2024)' },
            { name: 'NIDEC' },
            { name: 'Kiwa Machinery' },
            { name: 'NSD' },
            { name: 'ASAHI YUKIZAI KOGYO' },
            { name: 'PT Precision Tools service Indonesia' },
            { name: 'IDE' },
            { name: 'PT Sinto Indonesia' },
            { name: 'Shimada Electric' },
            { name: 'Asahi Sunac' },
            { name: 'PT Kyoritsu Electric Indonesia' },
            { name: 'HISAKA' },
            { name: 'NIKKEN' },
            { name: 'PT OTOMASI SOLUSI INTI' },
            { name: 'PT Precision Tools Service Indonesia' },
            { name: 'PT YOTANO TEKNIK INDONESIA' },
            { name: 'PT Chiyoda Kogyo Indonesia' },
            { name: 'Taiyo' },
            { name: 'JPC' },
            { name: 'DAIDO' },
            { name: 'Misumi' },
            { name: 'PT Zahwan Mitrateknindo' },
            { name: 'PT Wilisindomas Indah Makmur' },
            { name: 'PT Kurita Indonesia' },
            { name: 'TOUNETSU THAI' },
            { name: 'NBR' },
            { name: 'SWIF ASIA' },
            { name: 'LEGRAND' },
            { name: 'Tempens' },
            { name: 'HITACHI' },
            { name: 'Philips' },
            { name: 'SCHUH' },
            { name: 'PT Gandox Jaya Chemical' },
            { name: 'FUKUTA' },
            { name: 'NSV' },
            { name: 'FUJI' },
            { name: 'NIPPON STEEL & SUMIKIN BUSAN MATEX' },
            { name: 'OTG' },
            { name: 'NIPPON STEEL' },
            { name: 'COGNEX' },
            { name: 'SETSUYO' },
            { name: 'Lokal' },
            { name: 'MIHARA' },
            { name: 'KOYO' },
            { name: 'MAXITROL' },
            { name: 'SPARE PART BALANCING' },
            { name: 'GRAYHILL' },
            { name: 'DELTA' },
            { name: 'LIANG CHI' },
            { name: 'BOSTIK' },
            { name: 'AZBIL BERCA INDONESIA' },
            { name: 'YU SHINE PRECISION' },
            { name: 'YOSHITAKE' },
            { name: 'PT. MISUMI INDONESIA' },
            { name: 'CV. SINAR ARTHA' },
            { name: 'JAKI' },
            { name: 'LOKAL/ INDONESIA' },
            { name: 'KIT' },
            { name: 'PT. FANUC INDONESIA' },
            { name: 'PT Toyota Tsusho Mechanical & Engineering Service Indonesia' },
            { name: 'Fanuc' },
            { name: 'ZENBI MACHINERY' },
            { name: 'HIROSE' },
            { name: 'PT. Zenbi Machinery And Electronics Indonesia' },
            { name: 'PT Minezawa Trading Indonesia' },
            { name: 'BRIDGESTONE' },
            { name: 'PT. MINEZAWA TRADING INDONESIA' },
            { name: 'PT. ZENBI MACHINERY' },
            { name: 'YODOGAWA KEIKI' },
            { name: 'PT. Minezawa Trading Indonesia' },
            { name: 'Hirose Valves' },
            { name: 'FAWWAZ' },
            { name: 'PT. AMANO INDONESIA' },
            { name: 'ITOH DENKI' },
            { name: 'PT MORITA PRECISION INDONESIA' },
            { name: 'NICHIDEN' },
            { name: 'ISK' },
            { name: 'SWIFT ASIA' },
            { name: 'HORIUCHI' },
            { name: 'PT. SWIF ASIA' },
            { name: 'Azbil' },
            { name: 'Martin' },
            { name: 'NISSEI CORPORATION/ GTR' },
            { name: 'ELEKTRIM' },
            { name: 'ONDA' },
            { name: 'KIWA MACHINERY Co. Ltd.' },
            { name: 'PARKER TAIYO' },
            { name: 'PT.ZENBI MACHINERY' },
            { name: 'Nagano' },
            { name: 'MISTSUBISHI ELECTRIC' },
            { name: 'Sumitomo' },
            { name: 'HAKUSAN KIKO' },
            { name: 'CV. SINAR ARTHA TECNIC' },
            { name: 'TUNG LEE ELECTRICAL CO., LTD' },
            { name: 'UNI' },
            { name: 'UNI D' },
            { name: 'SAN ACE' },
            { name: 'HERATON' },
            { name: 'CHUBU MEIKOKU' },
            { name: 'KANZAKI KOKYUKOKI Mfg. Co.,Ltd' },
            { name: 'JUFAN' },
            { name: 'CV. Sinar Artha Technic' },
            { name: 'Kiwa Machinery Co., Ltd' },
            { name: 'Sougou Plant Co;LTD' },
            { name: 'SKCL' },
            { name: 'PARKER ENGINEERING' },
            { name: 'PT Keyence Indonesia' },
            { name: 'PHOENIX' },
            { name: 'SANWA DENKI' },
            { name: 'CV Qistech Plasindo' },
            { name: 'IFM' },
            { name: 'PT. YUTAKA ROBOT SYSTEM' },
            { name: 'PT Setsuyo Astec' },
            { name: 'UTICON' },
            { name: 'BROCO' },
            { name: 'NMB' },
            { name: 'SETSUYO ASTEC' },
            { name: 'PAP3T' },
            { name: 'PAPST' },
            { name: 'LAMBDA' },
            { name: 'FAN' },
            { name: 'PT. KEYENCE INDONESIA' },
            { name: 'Mitsubishi Electric' },
            { name: 'Nanaboshi' },
            { name: 'Keyence' },
            { name: 'SHIHLIN' },
            { name: 'NSD CORP' },
            { name: 'KSP' },
            { name: 'NICHIFU' },
            { name: 'NICIFU' },
            { name: 'NBS' },
            { name: 'Nord Lock' },
            { name: 'TOYOKIGEN' },
            { name: 'NITTA' },
            { name: 'NITTO' },
            { name: '3M ( SCOTH )' },
            { name: 'LLFA' },
            { name: 'CV. WAHYU ARTA TECNIC' },
            { name: 'CV Herry & Co' },
            { name: 'SENQCIA' },
            { name: 'PILAR PLATINUM MULIA' },
            { name: 'INDO MAKMUR' },
            { name: 'INDOMAKMUR' },
            { name: 'NORMAX' },
            { name: 'KIWA MACHINERY CO.LTD' },
            { name: 'PT. INDO BEARING' },
            { name: 'GRUNDFOS' },
            { name: 'CV. Beta Gaberta' },
            { name: 'EBARA' },
            { name: 'CUSTOM LOKAL' },
            { name: 'EZO' },
            { name: 'IJK' },
            { name: 'MOK' },
            { name: 'PARKER' },
            { name: 'PT. PUTRA PARUNG JAYA' },
            { name: 'KOY' },
            { name: 'BUKIT MAS BEARINDO' },
            { name: 'KOYO / FAG / NTN' },
            { name: 'NSK/NTN' },
            { name: 'tuffiadi' },
            { name: 'FAG / NTN /KOYO' },
            { name: 'HIWIN' },
            { name: 'ABBA' },
            { name: 'smc' },
            { name: 'THK/IKO' },
            { name: 'KANZAKI / IKO' },
            { name: 'CV. INTISUPPLIES MEGA PERKASA' },
            { name: 'PT Kawamura Indah' },
            { name: 'VALQUA' },
            { name: 'Custom' },
            { name: 'BETA GABERTA' },
            { name: 'NQK' },
            { name: 'TIGER SEAL' },
            { name: 'TAIYO PARKER' },
            { name: 'SAKAGAMI' },
            { name: 'VITON' },
            { name: 'TOKYO HATSUJYO' },
            { name: 'PT Inox Prima' },
            { name: 'TECO' },
            { name: 'AC MOTOREN GMBH' },
            { name: 'NIPPON STEEL & SUMIKIN BUSAN MATEX CO,.LTD' },
            { name: 'GROUNDFOS' },
            { name: 'CV BETA GABERTA MEKANINDO' },
            { name: 'cv. Herry & C0' },
            { name: 'CV. Wahyu Arta' },
            { name: 'HERRY & CO' },
            { name: 'TATUNG' },
            { name: 'AMANO' },
            { name: 'Chubu Meikiko . Co.Ltd' },
            { name: 'CHUBU MEIKIKOU . Co.Ltd' },
            { name: 'MEIKIKO' },
            { name: 'CHUBU' },
            { name: 'PT. ISK' },
            { name: 'DAIMA' },
            { name: 'HAMMERINDO' },
            { name: 'FUKOTA' },
            { name: 'MAKISHINKO' },
            { name: 'AICHI T0KEI' },
            { name: 'KUO CHUAN MACHINERY' },
            { name: 'SANKEN SANGYO' },
            { name: 'SENTA' },
            { name: 'SHINTO' },
            { name: 'Costum' },
            { name: 'PT. MONDYLIA AMERTA' },
            { name: 'CHUAN FAN' },
            { name: 'SIGA' },
            { name: 'YUTAKA DENSHI' },
            { name: 'Yu Shine Precision' },
            { name: 'YU SHIEN' },
            { name: 'PT. ZAHWAN' },
            { name: 'MEZ MOHELNICE' },
            { name: 'Yutaka Denshi' },
            { name: 'APISTE' },
            { name: 'NISSEI CORPORATION' },
            { name: 'MCN' },
            { name: 'Central Motor Wheel Of America' },
            { name: 'DAIKI CO. LTD' },
            { name: 'PT. JAYA INDUKSI ELEKTRIK' },
            { name: 'PT Swif Asia' },
            { name: 'CV WAHYU ARTHA' },
            { name: 'KITO' },
            { name: 'TKR' },
            { name: 'Tounetsu Thai Co Ltd' },
            { name: 'PT AMANO INDONESIA' },
            { name: 'PT Amano Indonesia' },
            { name: 'ANES IWATA' },
            { name: 'SHOWA DENKI' },
            { name: 'Ebara' },
            { name: 'PT Geronimo Sukses MAndiri' },
            { name: 'CV. Wahana Engineering/Geronimo' },
            { name: 'CNP' },
            { name: 'PT Geronimo Sukses Mandiri' },
            { name: 'YAMAHA' },
            { name: 'HITECH' },
            { name: 'Tounetsu Thai Co., Ltd' },
            { name: 'PT MEITOKU-WADAYAMA INDONESIA' },
            { name: 'NISSEI GTR' },
            { name: 'BONFIG' },
            { name: 'PT. KINARYA NUSANTARA SUKSESTY' },
            { name: 'ULVAC' },
            { name: 'Sougou Plant Co., LTD' }
        ]
    });


    await prisma.maker.createMany({
        data: [
            { name: 'Nippon Steel Trading Matex Co.,LTD' },
            { name: 'PT MEITOKU WADAYAMA INDONESIA' },
            { name: 'CV Wahyu Arta Technic' },
            { name: 'PT FAWWAZINDO GHINA PERSADA' },
            { name: 'PT UMETOKU INDONESIA' },
            { name: 'CV Beta Gaberta Mekanindo' },
            { name: 'PT Precision Tools service Indonesia' },
            { name: 'PT. SINAR MUTIARA CAKRABUANA' },
            { name: 'PT Swif Asia' },
            { name: 'PT Tempsens Asia Jaya' },
            { name: 'PT TEMPSENS ASIA JAYA' },
            { name: 'Toyotsu Machinery Corporation' },
            { name: 'Sankensangyo Co., Ltd' },
            { name: 'CV. UNITED CONTROL' },
            { name: 'PT Zenbi Machinery And Electronics Indonesia' },
            { name: 'PT Minezawa Trading Indonesia' },
            { name: 'CV Sinar Artha Technic' },
            { name: 'PT KINARYA NUSANTARA SUKSESTY' },
            { name: 'PT. BUKIT MAS BEARINDO' },
            { name: 'PT Precision Tools Service Indonesia' },
            { name: 'PT Inox Prima' },
            { name: 'PT. PANDU HYDRO PNEUMATIC' },
            { name: 'CV Intisupplies Mega Perkasa' },
            { name: 'Lucky Dragon International Co., Ltd.' },
            { name: 'Mitsui Kiko Co., Ltd' },
            { name: 'PT Pandu Hydro Pneumatics' },
            { name: 'PT Sinar Mutiara Cakrabuana' },
            { name: 'PT. Zahwan Mitrateknindo' },
            { name: 'PT DUTA SWARNA DWIPA' },
            { name: 'PT. ZAHWAN MITRATEKNINDO' },
            { name: 'PT ARTIUM ALBA RAYA' },
            { name: 'PANDU HYDRO PNEUMATIC' },
            { name: 'PT. INOX PRIMA' },
            { name: 'PT ARPHUS REKA MANDIRI' },
            { name: 'PT Misumi Indonesia' },
            { name: 'TOUNETSU THAI . Co Ltd.' },
            { name: 'PT. STAHLINDO SURFACING INDONESIA' },
            { name: 'CV. BUANA SINERGI ENGINEERING' },
            { name: 'PT. FAWWAZINDO GHINA PERSADA' },
            { name: 'PT. YKT GEAR' },
            { name: 'PT. SINTO INDONESIA' },
            { name: 'PT. HIMALAYA EVEREST JAYA' },
            { name: 'PT. SWIF ASIA' },
            { name: 'Kiwa Machinery Co., Ltd' },
            { name: 'PT. INDOBEARING PERKASA' },
            { name: 'PT TUFFIADI' },
            { name: 'TOYOTSU MACHINERY Corp.' },
            { name: 'PT. TUFFIADI' },
            { name: 'PT. MINEZAWA TRADING INDONESIA' },
            { name: 'PT Geronimo Sukses Mandiri' },
            { name: 'PT Bukit Mas Bearindo' },
            { name: 'CV Sinar Arta Technic' },
            { name: 'PT. Pandu Hydro Pneumatics' },
            { name: 'PT. PUSACO INTERNATIONAL' },
            { name: 'PT Indo makmur Mandiri' },
            { name: 'Kanzaki Kokyukoki Mfg Co Ltd' },
            { name: 'PT AMCO Multitech' },
            { name: 'CV UNITED CONTROLS' },
            { name: 'PT Fanuc Indonesia' },
            { name: 'PT Himalaya Everest Jaya' },
            { name: 'PT. NUMACHINDO' },
            { name: 'PT Numacindo Karsakharisma' },
            { name: 'CV. WIRA GRIYA MUSTIKA' },
            { name: 'DAIMA II' },
            { name: 'CV. WAHYU ARTHA' },
            { name: 'PT Indo Makmur Mandiri' },
            { name: 'CV Wira Griya Mustika' },
            { name: 'KUO CHUAN MACHINERY Corp. INDUSTRIAL CO.,LTD.' },
            { name: 'CV. Senta Andalan Kimia' },
            { name: 'PT. PANDU HYDRO' },
            { name: 'PT. SETSUYO ASTEC' },
            { name: 'PT. FLEXINDOMAS' },
            { name: 'CV Qistech Plasindo' },
            { name: 'PT INDO MAKMUR MANDIRI' },
            { name: 'PT Zenbi Machinery and Electronics Indonesia' },
            { name: 'PT. KOBELINDO COMPRESSORS' },
            { name: 'PT Traktor Nusantara' },
            { name: 'PT Axia Multi Sarana' },
            { name: 'PT. Creative Mitra Selaras Indonesia' },
            { name: 'CV Sinar artha Technic' },
            { name: 'PT Stark Asia Corporindo' },
            { name: 'CV. SENTA ANDALAN KIMIA' },
            { name: 'PT Daiichi Mandiri Automation' },
            { name: 'PT. MEGA TEKHNIK DHEALFIAN' },
            { name: 'PT Panel Bakti Sinarindo' },
            { name: 'PT Keyence Indonesia' },
            { name: 'PT. ELMECON MULTI KENCANA' },
            { name: 'PT Elmecon Multikencana' },
            { name: 'PT. NUMACHINDO KARSAKHARISMA' },
            { name: 'PT. AZBIL BERCA INDONESIA' },
            { name: 'PT FANUC INDONESIA' },
            { name: 'PT Toyota Tsusho Mechanical & Engineering Service Indonesia' },
            { name: 'PT KEYENCE INDONESIA' },
            { name: 'PT. KEYENCE INDONESIA' },
            { name: 'PT. FANUC INDONESIA' },
            { name: 'PT SETSUYO ASTEC' },
            { name: 'PT Setsuyo Astec' },
            { name: 'PT Hikari Automaton Indonesia' },
            { name: 'PT. Setsuyo Astec' },
            { name: 'ITOH DENKI' },
            { name: 'FANUC' },
            { name: 'TOYOTA TSUSHO CORPORATION' },
            { name: 'MENICS' },
            { name: 'PT Kawan Lama Sejahtera' },
            { name: 'MISUMI' },
            { name: 'PT. YUTAKA ROBOT SYSTEM INDONESIA' },
            { name: 'Ray Corporation Tokyo Branch' },
            { name: 'PT AZBIL BERCA' },
            { name: 'PT MINEZAWA TRADING INDONESIA' },
            { name: 'PT. ARTIUM ALBA RAYA' },
            { name: 'PT. INDOMAKMUR MANDIRI' },
            { name: 'INOX' },
            { name: 'PT. Precision Tools Service Indonesia' },
            { name: 'PT ZAHWAN MITRATEKNINDO' },
            { name: 'PT Amano Indonesia' },
            { name: 'PT Azbil Berca Indonesia' },
            { name: 'PT Yutaka Robot System Indonesia' },
            { name: 'JAYA INDUKSI' },
            { name: 'CV. UNITED CONTROLS' },
            { name: 'PT YUTAKA ROBOT SYSTEM INDONESIA' },
            { name: 'PT. Tuffiadi Semesta' },
            { name: 'TOYOTSU MACHINERY CORPORATION' },
            { name: 'Setiawan Tehnik' },
            { name: 'KUO CHUAN MACHINERY Industrial' },
            { name: 'PT Indobearing Perkasa' },
            { name: 'PT. Indobearing Perkasa' },
            { name: 'Shan Long Mechanical Engineering CO. Ltd' },
            { name: 'KUO CHUAN MACHINERY INDUSTRIAL CO.,LTD.' },
            { name: 'PT Mega Tekhnik Dhealfian' },
            { name: 'PT ELMECON' },
            { name: 'PT. Kobelindo Compressors' },
            { name: 'PT Taiyo Sinar Raya Teknik' },
            { name: 'PT. BIOTECH INDO GEMILANG' },
            { name: 'KUO CHUAN MACHINERY INDUSTRIAL CO.,LTD' },
            { name: 'CV SENTA ANDALAN KIMIA' },
            { name: 'PT Sinar Buana' },
            { name: 'PT Orugg Vision Indonesia' },
            { name: 'CV Bintang Mayoki' },
            { name: 'CV HERRY & CO' },
            { name: 'PT Intisupplies Mega Perkasa' },
            { name: 'Isuzu MFG Co Ltd' },
            { name: 'PT SINAR MUTIARA CAKRABUANA' },
            { name: 'PT Flexindomas' },
            { name: 'PT PUTRA PARUNG JAYA' },
            { name: 'PT. KINARYA NUSANTARA SUKSESTY' },
            { name: 'PT. ZENBI MACHINERY' },
            { name: 'PT ELMECON MULTIKENCANA' },
            { name: 'PT. Daichi Mandiri Automation' },
            { name: 'PT. ZIEKA TEKNIKATAMA INDONESIA' },
            { name: 'TOYOTSU MACHINERY' },
            { name: 'PT ELMECON MULTI KENCANA' },
            { name: 'PT ZIEKA TEKNIKATAMA INDONESIA' },
            { name: 'PT PT. KEYENCE INDONESIA Indonesia' },
            { name: 'CV Senta Andalan Kimia' },
            { name: 'PT INOX PRIMA' },
            { name: 'TOYOTSU MACHINERY CORPRORATION' },
            { name: 'CV WAHYU ARTA TECHNIC' },
            { name: 'PT TUFFIADI SEMESTA' },
            { name: 'SINTO' },
            { name: 'PT SINTO INDONESIA' },
            { name: 'PT Zahwan Mitrateknindo' },
            { name: 'CV. Intisupplies Mega Perkasa' },
            { name: '0' },
            { name: 'KINARYA' },
            { name: 'CV.SINAR ARTHA' },
            { name: 'PT MORITA PRECISION INDONESIA' },
            { name: 'PT Sinto Indonesia' },
            { name: 'PT Kyoritsu Electric Indonesia' },
            { name: 'PT OTOMASI SOLUSI INTI' },
            { name: 'PT YOTANO TEKNIK INDONESIA' },
            { name: 'PT Wilisindomas Indah Makmur' },
            { name: 'PT Kurita Indonesia' },
            { name: 'TOUNETSU THAI' },
            { name: 'PT. Victory Win Solusindo' },
            { name: 'PT. PUTRA PARUNG JAYA' },
            { name: 'PT Gandox Jaya Chemical' },
            { name: 'PT NUMACINDO KARSAKHARISMA' },
            { name: 'CV BINTANG MAYOKI' },
            { name: 'PT. ORUGG VISION INDONESIA' },
            { name: 'SMC' },
            { name: 'PT PANDU HYDRO PNEUMATIC' },
            { name: 'PT SETSUYO ASTEC INDONESIA' },
            { name: 'KUO CHUAN MACHINERY INDUSTRIAL CO LTD' },
            { name: 'PT. INDONESIA ROAD DEVELOPMENT' },
            { name: 'SAXON Test- and Tank- Equipment GmbH' },
            { name: 'PT. HIMAWAN PUTRA' },
            { name: 'YU SHINE PRECISION' },
            { name: 'CV UNITED CONTROL' },
            { name: 'PT. PELITA KARYA SUPPLINDO' },
            { name: 'Gading Nusa Persada' },
            { name: 'PT PELITA KARYA SUPLINDO' },
            { name: 'PT Pelita Karya Suplindo' },
            { name: 'PT. Zenbi Machinery And Electronics Indonesia' },
            { name: 'ZENBI MACHINERY' },
            { name: 'PT. PRECISION TOOL SERVICES INONESIA' },
            { name: 'PT. Minezawa Trading Indonesia' },
            { name: 'ISUZU MFG. CO., LTD.' },
            { name: 'SETSUYO ASTEC' },
            { name: 'PT. Fawwazindo Ghina Persada' },
            { name: 'PT. AMANO INDONESIA' },
            { name: 'ISK' },
            { name: 'PT.Azbil Berca Indonesia' },
            { name: 'PT JAYA INDUKSI' },
            { name: 'CV. SINAR ARTHA' },
            { name: 'PT. INDO MAKMUR' },
            { name: 'PT. Zenbi Machinery and Electronics Indonesia' },
            { name: 'CV. SINAR ARTHA TECNIC' },
            { name: 'YU SHIEN' },
            { name: 'Sougou Plant Co;LTD' },
            { name: 'PT Parker Engineering Indonesia' },
            { name: 'PT SARANA HEKSA AUTOMASI' },
            { name: 'Shan Long Mechanical Engineering CO,.LTD' },
            { name: 'PT. Yutaka Robot System Indonesia' },
            { name: 'PT. Keyence Indonesia' },
            { name: 'PT. YUTAKA ROBOT SYSTEM' },
            { name: 'PT SARANA HEKSA AUTOMASI FOKUSINDO' },
            { name: 'CV. Sinar Artha Technic' },
            { name: 'PT Arphus Reka Mandiri' },
            { name: 'CV Herry & Co' },
            { name: 'PT. SETIAWAN TEKNIK' },
            { name: 'PT. PILAR PLATINUM MULIA' },
            { name: 'PT. MISUMI' },
            { name: 'CV. Beta Gaberta' },
            { name: 'PT. Intisupplies Mega Perkasa' },
            { name: 'PT. DUTA SWARNA DWIPA' },
            { name: 'PT Tuffiadi Semesta' },
            { name: 'PT. PARKER INDONESIA' },
            { name: 'PT BUKIT MAS BEARINDO' },
            { name: 'NTN' },
            { name: 'CV. INTISUPPLIES MEGA PERKASA' },
            { name: 'PT. INTISUPPLIES MEGA PERKASA' },
            { name: 'INDO MAKMUR' },
            { name: 'BUKIT MAS BEARINDO' },
            { name: 'TUFFIADI' },
            { name: 'CV SINAR ARTHA' },
            { name: 'PT. TUFFIADI / INDOMAKMUR' },
            { name: 'PT Kawamura Indah' },
            { name: 'ISUZU MFG. CO. LTD' },
            { name: 'PT. MISUMI INDONESIA' },
            { name: 'PT Jaya Induksi Elektrik' },
            { name: 'cv. Herry & C0' },
            { name: 'CV. Wahyu Arta' },
            { name: 'HERRY & CO' },
            { name: 'CHUBU MEIKIKOU . Co.Ltd' },
            { name: 'CV. HERRY & Co.' },
            { name: 'Chubu Meikiko . Co.Ltd' },
            { name: 'PT. HIDUP SEJAHTERA ENGINEERING' },
            { name: 'PT SM-Cyclo Indonesia' },
            { name: 'PT. RODA HAMMERINDO' },
            { name: 'PT. RODA HAMMERINDO JAYA' },
            { name: 'CV. BETA GABERTA MEKANINDO' },
            { name: 'KUO CHUAN MACHINERY Corp.' },
            { name: 'CV. BETAGABERTA MEKANINDO' },
            { name: 'SENTA' },
            { name: 'PT AMANO INDONESIA' },
            { name: 'Toyotsu Machinery Corp' },
            { name: 'KUO CHUAN MACHINERY' },
            { name: 'PT. SINAR BUANA' },
            { name: 'Yu Shine Precision' },
            { name: 'PT. MONDYLIA AMERTA' },
            { name: 'YUTAKA DENSHI' },
            { name: 'Yutaka Denshi' },
            { name: 'PT SWIF ASIA' },
            { name: 'Central Motor Wheel Of America' },
            { name: 'PT. JAYA INDUKSI ELEKTRIK' },
            { name: 'CV BETA GABERTA MEKANINDO' },
            { name: 'Tounetsu Thai Co Ltd' },
            { name: 'PT MAKMUR META GRAHA DINAMIKA' },
            { name: 'PT Geronimo Sukses MAndiri' },
            { name: 'CV. Wahana Engineering/Geronimo' },
            { name: 'Tounetsu Thai Co., Ltd' },
            { name: 'PT MEITOKU-WADAYAMA INDONESIA' },
            { name: 'Sougou Plant Co., LTD' }
        ]
    });


    await prisma.machineArea.createMany({
        data: [
            { code: 'MA', 'name': 'MACHINING  ' },
            { code: 'UT', 'name': 'UTILITY' },
            { code: 'PA', 'name': 'MACHINING' },
            { code: 'GN', 'name': 'GENERAL' },
            { code: 'MA', 'name': 'PAINTING' },
            { code: 'PA', 'name': 'PAINTING' },
            { code: 'CM', 'name': 'LP' },
            { code: 'HT', 'name': 'HT' },
            { code: 'PS', 'name': '2ND MACHINING' },
            { code: 'CM', 'name': 'CASTING ' },
            { code: 'MA', 'name': 'MACHINING' },
            { code: 'CM', 'name': 'CASTING' },
            { code: 'ME', 'name': 'MELTING' }
        ]
    })
}

main()
    .catch((e) => {
        console.error(e);
        process.exit(1);
    })
    .finally(async () => {
        await prisma.$disconnect();
    });
